kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      name: frontend
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: siwanon/unicorn_test:unicorn_test.52
        imagePullPolicy: Always
        ports:
        - name: frontend
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
